import 'package:flutter/material.dart';
import 'package:futsal_finder/models/booking.dart';
import 'package:futsal_finder/models/futsal.dart';
import 'package:futsal_finder/services/auth_service.dart';
import 'package:futsal_finder/services/booking_service.dart';
import 'package:provider/provider.dart';

class BookingScreen extends StatefulWidget {
  final Futsal futsal;

  const BookingScreen({super.key, required this.futsal});

  @override
  State<BookingScreen> createState() => BookingScreenState();
}

class BookingScreenState extends State<BookingScreen> {
  DateTime _selectedDate = DateTime.now();
  TimeOfDay _selectedTime = TimeOfDay.now();
  final BookingService _bookingService = BookingService();

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Book Futsal'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            ListTile(
              title: Text('Selected Date: ${_selectedDate.toLocal()}'.split(' ')[0]),
              trailing: const Icon(Icons.calendar_today),
              onTap: () async {
                final DateTime? picked = await showDatePicker(
                  context: context,
                  initialDate: _selectedDate,
                  firstDate: DateTime.now(),
                  lastDate: DateTime(2101),
                );
                if (picked != null && picked != _selectedDate) {
                  setState(() {
                    _selectedDate = picked;
                  });
                }
              },
            ),
            ListTile(
              title: Text('Selected Time: ${_selectedTime.format(context)}'),
              trailing: const Icon(Icons.access_time),
              onTap: () async {
                final TimeOfDay? picked = await showTimePicker(
                  context: context,
                  initialTime: _selectedTime,
                );
                if (picked != null && picked != _selectedTime) {
                  setState(() {
                    _selectedTime = picked;
                  });
                }
              },
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                final formattedTime = _selectedTime.format(context);
                final booking = Booking(
                  id: '', // The ID will be generated by Firestore
                  futsalId: widget.futsal.id!,
                  userId: authService.user!.uid,
                  date: _selectedDate,
                  time: formattedTime,
                  status: 'confirmed',
                );

                await _bookingService.createBooking(booking);
                
                if (!context.mounted) return;

                await showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Booking Confirmed'),
                    content: const Text('Your booking has been successfully confirmed.'),
                    actions: [
                      TextButton(
                        onPressed: () {
                          Navigator.pop(context); // Dismiss the dialog
                        },
                        child: const Text('OK'),
                      ),
                    ],
                  ),
                );
                
                if (context.mounted) {
                  Navigator.pop(context);
                } // Go back to the previous screen
              },
              child: const Text('Confirm Booking'),
            ),
          ],
        ),
      ),
    );
  }
}
